quarkus:
  application:
    name: home-library-librarian
  http:
    port: 8080
  datasource:
    db-kind: mariadb
    jdbc:
      driver: org.mariadb.jdbc.Driver
      url: ${RDBMS_URL}
      min-size: 5
      max-size: 20
      initial-size: 5
      validation-query-sql: SELECT 1
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PWD}
  hibernate-orm:
    database:
      generation: update
    # log:
      # sql: true
    # dialect: org.hibernate.dialect.MariaDB103Dialect
    